import * as dat from "dat.gui";

export const gui = new dat.GUI({
  autoPlace: false,
});

export const sv = {
  pixiScreenshot: undefined,
  frame: 0,
  oneActiveImage: null,
  arcCont: null,
  animatedArc: null,
  workerDone: false,
  pApp: null,
  resizeAppToMe: null,
  resizeAppToMeWidth: null,
  resizeAppToMeHeight: null,
  pContainer: null,
  sceneContainer: null,
  sceneContainerFrame: null,
  sceneContainer2: null,
  sceneContainerFrame2: null,
  aPositionBuffer: null,
  ticker: null,
  frameRate: 60,
  spinnyBG: null,
  triangleMesh: null,
  instancePositionBuffer: null,
  totalTriangles: null,
  triangles: null,
  iconAtlas: null,
  spritesheet: null,
  sSheetTextures: [],
  sheets: [],
  canvasRecorder: null,
  p: null,
  setupDone: false,
  clock: null,
  pauseClock: 0,
  direction: 1,
  pauseTime: 2000,
  paused: false,

  startLoop: 1.01,
  endLoop: 1.99,
  stateStartTime: null,
  clearImage: null,
  stills: [],
  animUnderImgs: [],
  singleImgIcons: [],
  debugImgToggle: 0,
  slidingPieceImgs: [],
  manualScale: 1.0,
  transitionSpeed: 3000.0,
  transitionDelay: 0.5,
  speed: 0.01,
  color: false,
  fillColor: "#000",
  brandBlueConst: "#55d4ff",
  params: {
    // clipOutliers: false,
    // coU: 0,
    clipDarkOutliers: 0,
    clipLightOutliers: 0,
    scaleDynamically: true,
    sdU: 1,
    startInvisible: false,
    siU: 0,
  },
  totalSourceUploadNum: null,
  advanced: null,
  customShapeGraphics: null,
  circleGraphicLeft: null,
  circleGraphicRight: null,
  iconGraphic0: null,
  iconGraphic1: null,
  iconGraphic2: null,
  iconGraphic3: null,
  iconGraphic4: null,
  iconGraphic5: null,
  iconGraphic6: null,
  iconGraphic7: null,
  iconGraphic8: null,
  iconGraphic9: null,
  iconGraphic10: null,
  iconGraphic11: null,
  iconGraphic12: null,
  iconGraphic13: null,
  iconGraphic14: null,
  iconGraphic15: null,
  iconGraphic16: null,
  iconGraphic17: null,
  iconGraphic18: null,
  iconGraphic19: null,
  singleImgIconPaths: null,

  cTex: null,
  sTex: null,
  loadingSprite: null,
  loadingScreen: null,
  circles: [],
  shapes: [],
  shapes2: [],
  noiseTex: null,
  noisyValues: [],
  noisyMax: null,
  noisyMin: null,

  rowCount: null,
  colCount: null,
  totalCells: null,
  xExcess: null,
  yExcess: null,
  gridW: null,
  gridH: null,
  cellW: null,
  cellH: null,
  gridGutterMult: 1.0,
  gridResolutionMax: 200,
  gridResolutionBuffer: "5",
  gridResolution: "5",
  noiseOffset: 1.0,
  snappiness: 10.0,
  tlThresh1: 0.15,
  tlThresh1BUFFER: 0.01,
  tlThresh2: 0.25,
  tlThresh2BUFFER: 0.01,
  tlThresh3: 0.5,
  tlThresh3BUFFER: 0.01,

  testSVG: null,
  testImages: null,

  isRecording: false,
  recordDuration: 5,
  takeScreenshot: false,
  tempUploadFiles: [],

  // HTML elements
  inputElement: null,
  imgDiv: null,
};
